### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by datenteiler** [daviwil/terminal-tab-service#1]
1. Install Atom via Flatpak on openSUSE Tumbleweed
2. Open Atom (Flatpak) und install Terminal Tab Service
3. Run Atom and open a PowerShell script

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: linux 4.15.10-1-default
**Thrown From**: [terminal-tab-service](https://github.com/daviwil/terminal-tab-service) package 0.1.4

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /home/christian/.var/app/io.atom.Atom/data/packages/terminal-tab-service/node_modules/node-pty-prebuilt/lib/unixTerminal.js:227

Error: ioctl(2) failed.
    at UnixTerminal.resize (/packages/terminal-tab-service/node_modules/node-pty-prebuilt/lib/unixTerminal.js:227:13)
    at TerminalView._didResize (/packages/terminal-tab-service/lib/terminal-view.js:102:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
build 0.70.0 
busy-signal 1.4.3 
docker 0.8.0 
Hydrogen 2.3.0 
ide-powershell 0.1.0 
language-powershell 4.0.0 
terminal-tab-service 0.1.4 
```

**Comment by ChristianHartTE** [comment]
This issue reoccurs every time I resize the window in i3.

**Comment by slaterjon** [comment]
I was getting this same error on linux and mac.  After installing PowerShell Core 7.0 and restarting Atom the issue went away.
From what it looked like to me, it was trying to open a powershell command window for debugging and since i did not have powershell installed it couldn't do that.
Not sure this is the total fix for this but it did work for me.
https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0
