### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by ghost** [daviwil/terminal-tab-service#3]
Hi there, i am unable to install this package for atom.io. This results in the following error log:
https://pastebin.com/TsazJx01

The error message seems to point out that the culprit is node-gyp, i searched the web and found out that node-gyp is a bit tricky on windows and i tried to follow the steps described here:
https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

i also tried to update the node-gyp module in node.js as explained here:
https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp

Still i am unable to install the package :(

**Comment by aminya** [comment]
Same here:
```ps1
Installing “terminal-tab-service@0.1.4” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\Users\yahyaaba\AppData\Local\Temp\apm-install-dir-120118-9208-1xvsfpb.2g2h\node_modules\terminal-tab-service\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\yahyaaba\AppData\Local\Temp\apm-install-dir-120118-9208-1xvsfpb.2g2h\node_modules\terminal-tab-service\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\yahyaaba\AppData\Local\atom-nightly\app-1.46.0-nightly1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\yahyaaba\AppData\Local\atom-nightly\app-1.46.0-nightly1\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install No prebuilt binaries found (target=4.2.7 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:406:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\yahyaaba\\AppData\\Local\\atom-nightly\\app-1.46.0-nightly1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\yahyaaba\\AppData\\Local\\atom-nightly\\app-1.46.0-nightly1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\yahyaaba\AppData\Local\Temp\apm-install-dir-120118-9208-1xvsfpb.2g2h\node_modules\terminal-tab-service\node_modules\node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\yahyaaba\AppData\Local\Temp\apm-install-dir-120118-9208-1xvsfpb.2g2h\package.json'
npm WARN apm-install-dir-120118-9208-1xvsfpb.2g2h No description
npm WARN apm-install-dir-120118-9208-1xvsfpb.2g2h No repository field.
npm WARN apm-install-dir-120118-9208-1xvsfpb.2g2h No README data
npm WARN apm-install-dir-120118-9208-1xvsfpb.2g2h No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yahyaaba\.atom\.apm\_logs\2020-02-18T08_57_51_369Z-debug.log
```

**Comment by honeo** [comment]
The installation starts automatically as a dependent package of ide-powershell, but it fails for the same reason.
